import localFont from "next/font/local";
import "./globals.css";
import Tanstack from "@/Services/Tanstack";
import AuthProvider from "@/Services/AuthProvider";
import { Lora, Manrope } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "700"], // Specify the font weights you need
});

export const metadata = {
  title: "My Company",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className}  antialiased`}>
        <Tanstack>
          <AuthProvider>{children}</AuthProvider>
        </Tanstack>
      </body>
    </html>
  );
}
